export const mockEvents = [
  {
    id: '1',
    title: 'TechFest 2026 — Annual Tech Summit',
    description: 'The biggest annual technology festival bringing together innovators, developers, and entrepreneurs. Featuring keynotes from industry leaders, hands-on workshops, hackathons, and incredible networking opportunities. Explore cutting-edge AI, blockchain, cloud computing, and more.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    date: '2026-07-15',
    time: '09:00 AM',
    venue: 'NIT Auditorium, Hyderabad',
    category: 'Technology',
    fee: 299,
    seats: 500,
    organizer: 'ACM Student Chapter',
  },
  {
    id: '2',
    title: 'HackVerse 2026 — 36-Hour Hackathon',
    description: 'Join 500+ developers, designers, and innovators for an intense 36-hour hackathon. Build solutions for real-world problems across tracks including FinTech, HealthTech, EdTech, and Sustainability. Prizes worth ₹2,00,000 up for grabs!',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
    date: '2026-07-28',
    time: '10:00 AM',
    venue: 'IIIT Hyderabad Campus',
    category: 'Hackathon',
    fee: 199,
    seats: 300,
    organizer: 'Google Developer Student Club',
  },
  {
    id: '3',
    title: 'Cultural Fiesta — Annual College Fest',
    description: 'Experience three days of unmatched cultural extravaganza. Dance battles, music performances, fashion shows, fine arts, drama, and so much more. Celebrities, DJ nights, food stalls — the ultimate college cultural experience!',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
    date: '2026-08-05',
    time: '11:00 AM',
    venue: 'JNTU Open Air Theatre',
    category: 'Cultural',
    fee: 149,
    seats: 1000,
    organizer: 'Cultural Committee',
  },
  {
    id: '4',
    title: 'CodeSprint — Competitive Programming',
    description: 'Put your algorithmic thinking and coding skills to the test in this high-intensity competitive programming contest. Problems range from easy to expert. Compete individually or as a team of two. Certificates for all participants.',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    date: '2026-08-12',
    time: '02:00 PM',
    venue: 'CS Department Lab, VIT Vellore',
    category: 'Technology',
    fee: 99,
    seats: 200,
    organizer: 'Coding Club',
  },
  {
    id: '5',
    title: 'Business Conclave — Startup Pitching',
    description: 'Present your startup idea to a panel of experienced VCs and angel investors. Win funding, mentorship, and incubation support. Network with 200+ entrepreneurs, attend masterclasses on funding, scaling, and go-to-market strategies.',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
    date: '2026-08-20',
    time: '10:00 AM',
    venue: 'IIM Bangalore, Seminar Hall',
    category: 'Business',
    fee: 499,
    seats: 150,
    organizer: 'E-Cell IIM',
  },
  {
    id: '6',
    title: 'Sports Premier League — Inter-College',
    description: 'The grand inter-college sports championship featuring Cricket, Football, Basketball, Volleyball, Badminton, and Athletics. Compete for the coveted Champions Trophy and win exciting prizes. Open to all college students.',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
    date: '2026-09-01',
    time: '07:00 AM',
    venue: 'Gachibowli Stadium, Hyderabad',
    category: 'Sports',
    fee: 199,
    seats: 800,
    organizer: 'Sports Committee',
  },
]

export const categoryColors = {
  Technology: { bg: 'rgba(13, 61, 58, 0.08)', text: '#0d3d3a', border: 'rgba(13, 61, 58, 0.2)' },
  Hackathon: { bg: 'rgba(168, 75, 47, 0.08)', text: '#a84b2f', border: 'rgba(168, 75, 47, 0.2)' },
  Cultural: { bg: 'rgba(201, 146, 58, 0.08)', text: '#c9923a', border: 'rgba(201, 146, 58, 0.2)' },
  Business: { bg: 'rgba(20, 92, 87, 0.08)', text: '#145c57', border: 'rgba(20, 92, 87, 0.2)' },
  Sports: { bg: 'rgba(168, 75, 47, 0.08)', text: '#a84b2f', border: 'rgba(168, 75, 47, 0.2)' },
  Workshop: { bg: 'rgba(232, 176, 96, 0.08)', text: '#c9923a', border: 'rgba(232, 176, 96, 0.2)' },
}

export const categories = ['All', 'Technology', 'Hackathon', 'Cultural', 'Business', 'Sports', 'Workshop']
